# Generated by Django 5.0 on 2024-09-16 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productmodel",
            options={"verbose_name": "Product", "verbose_name_plural": "Products"},
        ),
    ]
