# Generated by Django 5.0 on 2024-09-18 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("favoriteList", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="favoritelist",
            old_name="userId",
            new_name="user",
        ),
    ]
