# Generated by Django 5.0 on 2024-09-17 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("whishlist", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="wishlist",
            old_name="userId",
            new_name="user",
        ),
    ]
