# Generated by Django 5.0 on 2024-09-17 17:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_productmodel_options"),
        ("whishlist", "0002_rename_userid_wishlist_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wishlist",
            name="product",
        ),
        migrations.AddField(
            model_name="wishlist",
            name="favorite_products",
            field=models.ManyToManyField(
                related_name="favorited_by", to="core.productmodel"
            ),
        ),
        migrations.AlterField(
            model_name="wishlist",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
