# Generated by Django 5.0 on 2024-09-17 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_productmodel_options"),
        (
            "whishlist",
            "0003_remove_wishlist_product_wishlist_favorite_products_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="wishlist",
            name="favorite_products",
            field=models.ManyToManyField(
                blank=True, related_name="favorited_by", to="core.productmodel"
            ),
        ),
    ]
