# Generated by Django 5.0 on 2024-09-17 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("whishlist", "0004_alter_wishlist_favorite_products"),
    ]

    operations = [
        migrations.DeleteModel(
            name="WishList",
        ),
    ]
